### ISSUE TITLE
Vendor Block eating Cards

### ISSUE THREAD

**Issue by ClockwerkKaiser** [notabadminer/UniversalCoins#1]
Just wanted to report that, in SMP tests on my server, my card (as well as cards owned by other players) get "eaten" by Vendor Blocks. 

When trying to purchase an item from the Vendor Block, the item cannot be purchased, and the player's card cannot be taken out. 

If the player exits the GUI at this point, he/she can no longer enter the GUI. Nor can any other player. 

We have repeated the bug multiple times before deciding to just not use Vendor Blocks anymore (until fixed, that is).

**Comment by notabadminer** [comment]
Is the issue with the latest release? Or the 1.7.10 branch?

**Comment by ClockwerkKaiser** [comment]
Oh! I'm sorry, I should've mentioned that! 

It's the latest 1.8.9 release.

**Comment by notabadminer** [comment]
No worries. I'll spend some time on this tonight or tomorrow. I need to test full functionality on the trade station, vending blocks, and atm. There were some changed from 1.7.10 to 1.8.9 that affect the way things work or in this case, don't work.

**Comment by notabadminer** [comment]
I've updated the releases with a new version that should fix this issue.
