### ISSUE TITLE
Malfunctioned?

### ISSUE THREAD

**Issue by masakitenchi** [notabadminer/UniversalCoins#11]
![2017-01-26_14 41 44](https://cloud.githubusercontent.com/assets/11086210/22322327/3c168c42-e3d6-11e6-8c04-99d28b69136d.png)
![2017-01-26_14 41 47](https://cloud.githubusercontent.com/assets/11086210/22322328/3ca7810c-e3d6-11e6-9667-6d1751ff7f53.png)

**Comment by masakitenchi** [comment]
Minecraft 1.7.10 with universalcoins-1.7.10-1.7.7.jar
remove other mods, leaving itself only also have the same problem.

**Comment by notabadminer** [comment]
I must have screwed something up. I'll take a look tonight after work. Can
you try the "/uc update" command to regenerate prices?

**Comment by masakitenchi** [comment]
It still cannot work.
Tested in 1.7.10-LiteLoader1.7.10-1.7.10-Forge10.13.4.1614-1.7.10 with universalcoins-1.7.10-1.7.7.jar only
![2017-01-26_23 45 47](https://cloud.githubusercontent.com/assets/11086210/22338449/56943f32-e422-11e6-96f0-838017a2afe1.png)
![2017-01-26_23 50 58](https://cloud.githubusercontent.com/assets/11086210/22338448/567e9df8-e422-11e6-9d52-c03e51dbd2bc.png)

**Comment by notabadminer** [comment]
ores are not priced by default. There are too many mods that double or
triple the ingots when processed

**Comment by masakitenchi** [comment]
Even if there's no mod could multiple the ingots produced?

**Comment by masakitenchi** [comment]
But Wood planks even cannot activate the buy/sell button

**Comment by notabadminer** [comment]
planks should work. I need a log to know what the issue is. I'm not having
issues on single player or multiplayer.

**Comment by masakitenchi** [comment]
How could I output a log?
I just found this line: [00:19:55] [Server thread/INFO]: Universal Coins: pricelists saved.
By the way, now that you said ores and ingots cannot be bought or sold, why not a player use the multiplied ingots crafting Iron doors etc. and it now can be sold to earn extra money. How could the mod prevent this from happening?
