### ISSUE TITLE
A bug in UniversalCoins-1.12.2-0.9.0

### ISSUE THREAD

**Issue by AmicBeam** [notabadminer/UniversalCoins#17]
When throwing the items out from vendor_block or vendor_frame, or pressing left to average them, that items can be double.

**Comment by AsulconS** [comment]
I've also noticed that bug. It happens with any kinda item inside them.

**Comment by notabadminer** [comment]
Looking into it

**Comment by notabadminer** [comment]
this bug has been resolved
