### ISSUE TITLE
Cannot get .jar file for MC 1.7.10 updates

### ISSUE THREAD

**Issue by Dovencio** [notabadminer/UniversalCoins#6]
I cannot seem to get the .jar files for Minecraft 1.7.10 files. I could only get the .zip files.

**Comment by notabadminer** [comment]
looks like the jar files were lost during the move.  cc3768 contacted me a couple months ago and wanted to maintain the project while I took some time off from coding. I haven't seen any updates though. You can find the 1.7.10 files here: https://github.com/cc3768/UniversalCoinsMod/releases

**Comment by Dovencio** [comment]
Did you just add a jar because when I clicked on the link on your forum it was not like that. It had only the .zip files.

**Comment by notabadminer** [comment]
Yes. I figured I'd edit the latest tag to add the jar. It will hopefully
reduce the amount of "where are the files?" emails I get ☺

**Comment by Dovencio** [comment]
Ya, I looked for an hour for it and struggled to add an issue because I did not know that you can turn them off.

**Comment by notabadminer** [comment]
I didn't even notice that the issues were disabled. Sorry. I re-enabled them.

**Comment by Dovencio** [comment]
it is okay thanks though
